import React from 'react'
import './loading.scss'

export function Loading() {
  return (
    <div className="loading-wrapper">
      <div className="loadingio-spinner-ellipsis-at9d1qrdcj">
        <div className="ldio-g1owrnsw64e">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  )
}
// /* <style type="text/css"> */
// /* @keyframes ldio-cqyhy901iqt {
//    0% { transform: translate(12px,80px) scale(0); }
//   25% { transform: translate(12px,80px) scale(0); }
//   50% { transform: translate(12px,80px) scale(1); }
//   75% { transform: translate(80px,80px) scale(1); }
//  100% { transform: translate(148px,80px) scale(1); }
// }
// @keyframes ldio-cqyhy901iqt-r {
//    0% { transform: translate(148px,80px) scale(1): }
//  100% { transform: translate(148px,80px) scale(0); }
// }
// @keyframes ldio-cqyhy901iqt-c {
//    0% { background: #1d3f72 }
//   25% { background: #71c2cc }
//   50% { background: #d8ebf9 }
//   75% { background: #5699d2 }
//  100% { background: #1d3f72 }
// }
// .ldio-cqyhy901iqt div {
//   position: absolute;
//   width: 40px;
//   height: 40px;
//   border-radius: 50%;
//   transform: translate(80px,80px) scale(1);
//   background: #1d3f72;
//   animation: ldio-cqyhy901iqt 5s infinite cubic-bezier(0,0.5,0.5,1);
// }
// .ldio-cqyhy901iqt div:nth-child(1) {
//   background: #5699d2;
//   transform: translate(148px,80px) scale(1);
//   animation: ldio-cqyhy901iqt-r 1.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-cqyhy901iqt-c 5s infinite step-start;
// }.ldio-cqyhy901iqt div:nth-child(2) {
//   animation-delay: -1.25s;
//   background: #1d3f72;
// }.ldio-cqyhy901iqt div:nth-child(3) {
//   animation-delay: -2.5s;
//   background: #5699d2;
// }.ldio-cqyhy901iqt div:nth-child(4) {
//   animation-delay: -3.75s;
//   background: #d8ebf9;
// }.ldio-cqyhy901iqt div:nth-child(5) {
//   animation-delay: -5s;
//   background: #71c2cc;
// }
// .loadingio-spinner-ellipsis-q00v5g1uuo {
//   width: 200px;
//   height: 200px;
//   display: inline-block;
//   overflow: hidden;
//   background: #f1f2f3;
// }
// .ldio-cqyhy901iqt {
//   width: 100%;
//   height: 100%;
//   position: relative;
//   transform: translateZ(0) scale(1);
//   backface-visibility: hidden;
//   transform-origin: 0 0; /* see note above */
// // }
// // .ldio-cqyhy901iqt div { box-sizing: content-box; }
// // /* generated by https://loading.io/ */
// // </style> */}
// // 	)
// // }
